### ISSUE TITLE
NPE when downloading the plan

### ISSUE THREAD

**Issue by wirthandras** [wirthandras/shifts#31]
java.lang.NullPointerException: null
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[na:1.8.0_191]
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) ~[na:1.8.0_191]
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107) ~[na:1.8.0_191]
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) ~[na:1.8.0_191]
	at sun.font.SunFontManager$2.run(SunFontManager.java:431) ~[na:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_191]
	at sun.font.SunFontManager.<init>(SunFontManager.java:376) ~[na:1.8.0_191]
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[na:1.8.0_191]
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57) ~[na:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_191]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_191]
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) ~[na:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_191]
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) ~[na:1.8.0_191]
	at java.awt.Font.getFont2D(Font.java:491) ~[na:1.8.0_191]
	at java.awt.Font.canDisplayUpTo(Font.java:2060) ~[na:1.8.0_191]
	at java.awt.font.TextLayout.singleFont(TextLayout.java:470) ~[na:1.8.0_191]
	at java.awt.font.TextLayout.<init>(TextLayout.java:531) ~[na:1.8.0_191]
	at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:275) ~[poi-3.15.jar!/:3.15]
	at org.apache.poi.ss.util.SheetUtil.getColumnWidth(SheetUtil.java:250) ~[poi-3.15.jar!/:3.15]
	at org.apache.poi.ss.util.SheetUtil.getColumnWidth(SheetUtil.java:235) ~[poi-3.15.jar!/:3.15]
	at org.apache.poi.hssf.usermodel.HSSFSheet.autoSizeColumn(HSSFSheet.java:2164) ~[poi-3.15.jar!/:3.15]
	at org.apache.poi.hssf.usermodel.HSSFSheet.autoSizeColumn(HSSFSheet.java:2146) ~[poi-3.15.jar!/:3.15]
	at hu.wirthandras.shifts.services.generator.ExcelGenerator.normalizeBorder(ExcelGenerator.java:84) ~[classes!/:0.0.1-SNAPSHOT]
	at hu.wirthandras.shifts.services.generator.ExcelGenerator.generateOneSheet(ExcelGenerator.java:79) ~[classes!/:0.0.1-SNAPSHOT]
	at hu.wirthandras.shifts.services.generator.ExcelGenerator.generateSheet(ExcelGenerator.java:62) ~[classes!/:0.0.1-SNAPSHOT]
	at hu.wirthandras.shifts.services.generator.ExcelGenerator.generate(ExcelGenerator.java:52) ~[classes!/:0.0.1-SNAPSHOT]
	at hu.wirthandras.shifts.services.SpreadSheetService.downloadPlan(SpreadSheetService.java:53) ~[classes!/:0.0.1-SNAPSHOT]
	at hu.wirthandras.shifts.contoller.GenerateController.downloadPlan(GenerateController.java:34) ~[classes!/:0.0.1-SNAPSHOT]

**Comment by wirthandras** [comment]
The issue is related to alpine docker container -> no fonts in the alpine base image.
Install the ttf-dejavu to docker image

**Comment by wirthandras** [comment]
Problem fixed with:2d462470a1d33df8396598247dca6c6cff7eef62
